--
-- PostgreSQL database dump
--

-- Dumped from database version 15.6
-- Dumped by pg_dump version 15.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA public;


--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: article; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.article (
    "Id" bigint NOT NULL,
    "Created_At" timestamp with time zone DEFAULT now() NOT NULL,
    "Name" text,
    "Price" double precision,
    "Quantity" double precision,
    "Discount" real,
    "Total" double precision,
    "Category" text DEFAULT ''::text,
    "Purchase_Date" date,
    "Receipt_Id" bigint,
    "Unit" text DEFAULT ''::text,
    "Base_Unit" double precision,
    "Price_Base_Unit" double precision
);


--
-- Name: article_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.article ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.article_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: profile; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.profile (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: profile_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: receipt; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.receipt (
    "Id" bigint NOT NULL,
    "Created_At" timestamp with time zone DEFAULT now() NOT NULL,
    "Corp" text,
    "Total_Receipt" double precision DEFAULT '0'::double precision,
    "Purchase_Date" date,
    "Uuid" text,
    "Total_Calculated" double precision,
    "Total_R_Open_Ai" bigint,
    "Total_R_Extract" bigint,
    "Id_Profile" bigint
);


--
-- Name: COLUMN receipt."Uuid"; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.receipt."Uuid" IS 'Uuid from backend';


--
-- Name: receipt_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.receipt ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."receipt_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recipe; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recipe (
    "Title" text NOT NULL,
    "Description" text NOT NULL,
    "Cooking_Time" text NOT NULL,
    "Category" text NOT NULL,
    "Serving" integer NOT NULL,
    "Color" text NOT NULL,
    "Ingredient" text[] NOT NULL,
    "Step_List" text[] NOT NULL,
    "Image" text,
    "Id" bigint NOT NULL,
    "Id_Profile" bigint
);


--
-- Name: recipe_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.recipe ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."recipe_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: article; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.article ("Id", "Created_At", "Name", "Price", "Quantity", "Discount", "Total", "Category", "Purchase_Date", "Receipt_Id", "Unit", "Base_Unit", "Price_Base_Unit") FROM stdin;
1872	2026-02-20 11:08:03.629784+00	Betty Bossi Trockenbackhefe 3x7g	0.95	1	0	0.95	Backwaren und Getreide	2026-02-13	116	3x7g	\N	\N
1873	2026-02-20 11:08:03.629784+00	Villars Choco-Köpfli zartbitter 4x30g	3.95	1	3.15	0.8	Snacks, Apero und Süßwaren	2026-02-13	116	4x30g	\N	\N
1874	2026-02-20 11:08:03.629784+00	Coop Tortilla Chips Nature 300G	1.65	1	0	1.65	Snacks, Apero und Süßwaren	2026-02-13	116	300g	\N	\N
1875	2026-02-20 11:08:03.629784+00	Lemon Soda la Limonata 4x33cl	4.95	1	0	4.95	Getränke (alkoholisch & alkoholfrei)	2026-02-13	116	4x33cl	\N	\N
1876	2026-02-20 11:08:03.629784+00	Feldschlösschen Weizen Alk.frei 6x50CL	11.95	1	0	11.95	Getränke (alkoholisch & alkoholfrei)	2026-02-13	116	6x50cl	\N	\N
1877	2026-02-20 11:08:03.629784+00	Feldschlösschen alk.frei Zitrone DS 6x50	11.95	0	-11.95	11.95	Getränke (alkoholisch & alkoholfrei)	2026-02-13	116	stk	\N	\N
1878	2026-02-20 11:08:03.629784+00	Appenzeller Bier Quöllfrisch DS 6x50CL	10.95	1	1	9.95	Getränke (alkoholisch & alkoholfrei)	2026-02-13	116	6x50cl	\N	\N
1879	2026-02-20 11:08:03.629784+00	Asahi Super Dry 4x33CL	10.5	1	1	9.5	Getränke (alkoholisch & alkoholfrei)	2026-02-13	116	4x33cl	\N	\N
1880	2026-02-20 11:08:03.629784+00	Sun Spülglanz, 2 x 500 ml, Duo	11.8	1	7.95	3.85	Reinigungsmittel und Haushaltsreiniger	2026-02-13	116	2x500ml	\N	\N
1881	2026-02-20 11:08:03.629784+00	Country Riegel Crunchy Honey 12x19g	3.8	1	0	3.8	Snacks, Apero und Süßwaren	2026-02-13	116	12x19g	\N	\N
1882	2026-02-20 11:08:03.629784+00	Country Riegel Peanut Caramel 6x26g	3.5	1	0	3.5	Snacks, Apero und Süßwaren	2026-02-13	116	6x26g	\N	\N
1864	2026-02-20 11:08:03.629784+00	Naturafarm Kalbscipollata 6 Stück 150G	5.25	1	0	5.25	Fleisch, Fisch und pflanzliche Proteine	2026-02-13	116	6stk 150g	\N	\N
1863	2026-02-20 11:08:03.629784+00	R&L Mega Buns Rustico 330G	2.95	1	0	2.95	Backwaren und Getreide	2026-02-13	116	330g	\N	\N
1865	2026-02-20 11:08:03.629784+00	Bio Saisonbirnen offen 130	1.3	0.218	0	0.2834	Obst und Gemüse	2026-02-13	116	0.218kg	\N	\N
1866	2026-02-20 11:08:03.629784+00	Zwiebeln Bund	0.7	1	0	0.7	Obst und Gemüse	2026-02-13	116	stk	\N	\N
1867	2026-02-20 11:08:03.629784+00	Bio Broccoli offen PLU 654	1.65	0.374	0	0.6171	Obst und Gemüse	2026-02-13	116	0.374kg	\N	\N
1868	2026-02-20 11:08:03.629784+00	Coop Champignons geschnitten 114G	0.95	1	0	0.95	Obst und Gemüse	2026-02-13	116	114g	\N	\N
1869	2026-02-20 11:08:03.629784+00	Bio 365 Basmati Rice MH 500G	2	1	0	2	Backwaren und Getreide	2026-02-13	116	500g	\N	\N
1870	2026-02-20 11:08:03.629784+00	Naturaplan Bio Sesamöl 250ML	6.95	1	0	6.95	Gewürze, Kräuter und Saucen	2026-02-13	116	250ml	\N	\N
1871	2026-02-20 11:08:03.629784+00	Betty Bossi Backpulver 4x15g	0.95	1	0	0.95	Backwaren und Getreide	2026-02-13	116	4x15g	\N	\N
\.


--
-- Data for Name: profile; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.profile (id, created_at) FROM stdin;
1	2024-12-07 19:07:21+00
\.


--
-- Data for Name: receipt; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.receipt ("Id", "Created_At", "Corp", "Total_Receipt", "Purchase_Date", "Uuid", "Total_Calculated", "Total_R_Open_Ai", "Total_R_Extract", "Id_Profile") FROM stdin;
116	2026-02-20 11:08:03.582269+00	Coop	70.65	2026-02-13	9a125e4b-327f-402d-8292-b652d5ce34af	\N	\N	\N	\N
\.


--
-- Data for Name: recipe; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.recipe ("Title", "Description", "Cooking_Time", "Category", "Serving", "Color", "Ingredient", "Step_List", "Image", "Id", "Id_Profile") FROM stdin;
\.


--
-- Name: article_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.article_id_seq', 1920, true);


--
-- Name: profile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.profile_id_seq', 1, true);


--
-- Name: receipt_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."receipt_Id_seq"', 119, true);


--
-- Name: recipe_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."recipe_Id_seq"', 1, false);


--
-- Name: article article_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.article
    ADD CONSTRAINT article_id_key UNIQUE ("Id");


--
-- Name: article article_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.article
    ADD CONSTRAINT article_pkey PRIMARY KEY ("Id");


--
-- Name: profile profile_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile
    ADD CONSTRAINT profile_pkey PRIMARY KEY (id);


--
-- Name: receipt receipt_Id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.receipt
    ADD CONSTRAINT "receipt_Id_key" UNIQUE ("Id");


--
-- Name: receipt receipt_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.receipt
    ADD CONSTRAINT receipt_pkey PRIMARY KEY ("Id");


--
-- Name: recipe recipe_Id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recipe
    ADD CONSTRAINT "recipe_Id_key" UNIQUE ("Id");


--
-- Name: recipe recipe_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recipe
    ADD CONSTRAINT recipe_pkey PRIMARY KEY ("Id");


--
-- Name: article article_Receipt_Id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.article
    ADD CONSTRAINT "article_Receipt_Id_fkey" FOREIGN KEY ("Receipt_Id") REFERENCES public.receipt("Id") ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: receipt receipt_Id_Profile_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.receipt
    ADD CONSTRAINT "receipt_Id_Profile_fkey" FOREIGN KEY ("Id_Profile") REFERENCES public.profile(id) ON DELETE CASCADE;


--
-- Name: recipe recipe_Id_Profile_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recipe
    ADD CONSTRAINT "recipe_Id_Profile_fkey" FOREIGN KEY ("Id_Profile") REFERENCES public.profile(id) ON DELETE CASCADE;


--
-- Name: profile; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.profile ENABLE ROW LEVEL SECURITY;

--
-- PostgreSQL database dump complete
--

