--
-- PostgreSQL database dump
--

-- Dumped from database version 15.6
-- Dumped by pg_dump version 15.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA public;


--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: article; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.article (
    "Id" bigint NOT NULL,
    "Created_At" timestamp with time zone DEFAULT now() NOT NULL,
    "Name" text,
    "Price" double precision,
    "Quantity" double precision,
    "Discount" real,
    "Total" double precision,
    "Category" text DEFAULT ''::text,
    "Purchase_Date" date,
    "Receipt_Id" bigint,
    "Unit" text DEFAULT ''::text,
    "Base_Unit" double precision,
    "Price_Base_Unit" double precision
);


--
-- Name: article_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.article ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.article_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: integration_config; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.integration_config (
    key text NOT NULL,
    value_text text,
    value_encrypted text,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: profile; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.profile (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: profile_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: receipt; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.receipt (
    "Id" bigint NOT NULL,
    "Created_At" timestamp with time zone DEFAULT now() NOT NULL,
    "Corp" text,
    "Total_Receipt" double precision DEFAULT '0'::double precision,
    "Purchase_Date" date,
    "Uuid" text,
    "Total_Calculated" double precision,
    "Total_R_Open_Ai" bigint,
    "Total_R_Extract" bigint,
    "Id_Profile" bigint,
    "External_Source" text,
    "External_Receipt_Id" text
);


--
-- Name: COLUMN receipt."Uuid"; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.receipt."Uuid" IS 'Uuid from backend';


--
-- Name: receipt_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.receipt ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."receipt_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recipe; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recipe (
    "Title" text NOT NULL,
    "Description" text NOT NULL,
    "Cooking_Time" text NOT NULL,
    "Category" text NOT NULL,
    "Serving" integer NOT NULL,
    "Color" text NOT NULL,
    "Ingredient" text[] NOT NULL,
    "Step_List" text[] NOT NULL,
    "Image" text,
    "Id" bigint NOT NULL,
    "Id_Profile" bigint
);


--
-- Name: recipe_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.recipe ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."recipe_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: article; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.article ("Id", "Created_At", "Name", "Price", "Quantity", "Discount", "Total", "Category", "Purchase_Date", "Receipt_Id", "Unit", "Base_Unit", "Price_Base_Unit") FROM stdin;
2064	2026-04-29 12:19:02.293008+00	Bio Vollkorntoast 500G	5	1	3.5	1.5	Backwaren und Getreide	2026-04-27	136	g	\N	\N
2081	2026-04-29 12:19:02.295227+00	Broccoli offen PLU 172	2.2	0.456	2.2	0	Obst und Gem├╝se	2026-04-27	136	kg	\N	\N
2355	2026-04-29 12:57:24.630663+00	BB Bio Pizzateig eckig 550G	4.55	1	0	4.55	Backwaren und Getreide	2026-03-10	166	g	\N	\N
2132	2026-04-29 12:31:18.228305+00	BB Dinkel Pizzateig rechteckig 550G	3.5	1	0	3.5	Backwaren und Getreide	2026-04-13	146	g	\N	\N
2292	2026-04-29 12:41:39.288012+00	BB Pizzateig Rustico ausg. eckig 550G	3.95	1	0	3.95	Backwaren und Getreide	2026-03-20	158	g	\N	\N
2187	2026-04-29 12:31:56.822026+00	Bio 365 MH Quinoa Tricolore 400G	3.55	1	0	3.55	Andere	2026-04-08	149	g	\N	\N
2248	2026-04-29 12:40:00.821232+00	Bio Avocado St	2.15	1	0	2.15	Andere	2026-03-27	154	stk	\N	\N
2249	2026-04-29 12:40:00.821232+00	Bio Avocado St	2.15	1	0	2.15	Andere	2026-03-27	154	stk	\N	\N
2108	2026-04-29 12:25:06.653659+00	Butterweggli 70G	0.75	1	0	0.75	Backwaren und Getreide	2026-04-22	141	g	\N	\N
2253	2026-04-29 12:40:00.821232+00	Bio Avocado St	2.15	0	1.3	0	Andere	2026-03-27	154	stk	\N	\N
2077	2026-04-29 12:19:02.294661+00	Bio Birne 500g (ohne Knospe)	3.2	1	0	3.2	Obst und Gemuese	2026-04-27	136	g	\N	\N
2397	2026-04-29 12:57:59.964898+00	Bio Broccoli offen PLU 654	1.25	0.284	0	0.355	Obst und Gemuese	2026-03-05	169	g	\N	\N
2170	2026-04-29 12:31:37.745747+00	Bio Buttergipfel rustico 43G	1.1	1	0	1.1	Andere	2026-04-09	148	g	\N	\N
2075	2026-04-29 12:19:02.294094+00	Coop Hinterschinken 180G	4.95	1	0	4.95	Fleisch, Fisch und pflanzliche Proteine	2026-04-27	136	g	\N	\N
2329	2026-04-29 12:51:44.322654+00	Bio Dinkelbr├Âtli 80G	1.5	1	0	1.5	Andere	2026-03-13	163	g	\N	\N
2304	2026-04-29 12:41:39.288012+00	Bio Fenchel offen 642	1.15	0.262	0	0.3013	Obst und Gemuese	2026-03-20	158	g	\N	\N
2101	2026-04-29 12:19:29.713434+00	Bilz Chill & Relax alk.frei DS 6x33CL	9.95	1	0	9.95	Getr├ñnke (alkoholisch & alkoholfrei)	2026-04-23	139	cl	\N	\N
2056	2026-04-29 12:18:39.657762+00	Butterweggli 70G	0.75	1	0	0.75	Backwaren und Getreide	2026-04-29	135	g	\N	\N
2100	2026-04-29 12:19:29.713434+00	Bilz Stellare Limone alk. frei DS 6x33CL	9.95	1	0	9.95	Getr├ñnke (alkoholisch & alkoholfrei)	2026-04-23	139	cl	\N	\N
2109	2026-04-29 12:25:06.653659+00	Evian 75CL	1.15	1	0	1.15	Getr├ñnke (alkoholisch & alkoholfrei)	2026-04-22	141	cl	\N	\N
2218	2026-04-29 12:39:24.13308+00	Coop Feinkristall-Zucker IP Suisse 1KG	1.8	1	0	1.8	Andere	2026-04-02	152	kg	\N	\N
2338	2026-04-29 12:51:44.324244+00	Karabinerhaken 5x50mm Blackline	3.7	1	0	3.7	Andere	2026-03-13	163	mm	\N	\N
2330	2026-04-29 12:51:44.323193+00	Laugengipfel mit Kernen 70G	1.3	1	0	1.3	Backwaren und Getreide	2026-03-13	163	g	\N	\N
2078	2026-04-29 12:19:02.294661+00	Max Havelaar Datteln 300g	4.5	1	0	4.5	Andere	2026-04-27	136	g	\N	\N
2310	2026-04-29 12:41:39.288012+00	Hydrate+ Reload 75CL	1.95	1	1.75	0.2	Getr├ñnke (alkoholisch & alkoholfrei)	2026-03-20	158	cl	\N	\N
2069	2026-04-29 12:19:02.293569+00	Coop IPS Cr├¿me Fra├«che Kr├ñuter 2x200g	5.8	1	4.6	1.2	Milchprodukte, Eier und Alternativen	2026-04-27	136	g	\N	\N
2068	2026-04-29 12:19:02.293008+00	Coop IPS Milchdrink UHT 1.5% 6x1L Edge	9.6	1	0	9.6	Milchprodukte, Eier und Alternativen	2026-04-27	136	l	\N	\N
2386	2026-04-29 12:57:39.84157+00	Coop Havelaar Milder Orangensaft 4x1l	7.8	1	0	7.8	Getr├ñnke (alkoholisch & alkoholfrei)	2026-03-06	167	l	\N	\N
2072	2026-04-29 12:19:02.294094+00	Coop Mollini Mozzarella Stange 300g	2.9	1	0	2.9	Milchprodukte, Eier und Alternativen	2026-04-27	136	g	\N	\N
2385	2026-04-29 12:57:39.84157+00	Coop Havelaar Multivitaminsaft 4x1l	7.4	1	0	7.4	Getr├ñnke (alkoholisch & alkoholfrei)	2026-03-06	167	l	\N	\N
2091	2026-04-29 12:19:02.296317+00	Fisherman's Friend Spearmint o/Z 2x25g	3.3	1	0	3.3	Andere	2026-04-27	136	g	\N	\N
2086	2026-04-29 12:19:02.295745+00	FRECHE FREUNDE Apfel Sauerkirs.S├╝sskarto	1.95	1	1.55	0.4	Andere	2026-04-27	136	stk	\N	\N
2255	2026-04-29 12:40:56.870544+00	M├Âvenpick Stracciatella 165ml	4.5	1	0	4.5	Tiefkuehlprodukte	2026-03-26	155	ml	\N	\N
2179	2026-04-29 12:31:56.821506+00	Naturaplan Bio Saurer Halbrahm 15% 200g	1.8	1	0	1.8	Milchprodukte, Eier und Alternativen	2026-04-08	149	g	\N	\N
2093	2026-04-29 12:19:09.367246+00	Naturaplan Bio Schnitzwasser 50CL	1	1	0	1	Andere	2026-04-25	137	cl	\N	\N
2067	2026-04-29 12:19:02.293008+00	Naturaplan Bio Vollmilch UHT 6x1l	11.7	1	0	11.7	Andere	2026-04-27	136	l	\N	\N
2085	2026-04-29 12:19:02.295745+00	Nectaflor Mandeln Tomate & Rosma. 100G	6.6	1	0	6.6	Andere	2026-04-27	136	g	\N	\N
2171	2026-04-29 12:31:37.745747+00	Ovomaltine Ostereili 300G	14.35	1	5.7	8.65	Andere	2026-04-09	148	g	\N	\N
2165	2026-04-29 12:31:29.230977+00	Bio Kartoffeln gr├╝n 1KG CH	2.9	1	0	2.9	Obst und Gemuese	2026-04-10	147	kg	\N	\N
2168	2026-04-29 12:31:37.745747+00	Bio Landbr├Âtli 90G	1.3	1	0	1.3	Obst und Gemuese	2026-04-09	148	g	\N	\N
2115	2026-04-29 12:25:24.286432+00	Bio Max Havelaar Bananen offen 101	1.75	0.546	0	0.9555	Obst und Gemuese	2026-04-18	143	stk	\N	\N
2141	2026-04-29 12:31:18.228886+00	Bio Max Havelaar Bananen offen 101	1.5	0.474	0	0.711	Obst und Gemuese	2026-04-13	146	stk	\N	\N
2063	2026-04-29 12:19:02.292482+00	HB Bio Fladenbrot 300G	2.95	1	0	2.95	Backwaren und Getreide	2026-04-27	136	g	\N	\N
2087	2026-04-29 12:19:02.295745+00	Hipp M├╝esli Pfirsi.Ban.i.Apfel Jogh.120g	2.15	2	4.3	0	Milchprodukte, Eier und Alternativen	2026-04-27	136	g	\N	\N
2134	2026-04-29 12:31:18.228305+00	Coop Mollini Mozzarella Mini 2x145g	3.6	1	0.9	2.7	Milchprodukte, Eier und Alternativen	2026-04-13	146	g	\N	\N
2364	2026-04-29 12:57:24.631204+00	Coop Pasteten-F├╝llung 440G	4.2	1	0	4.2	Andere	2026-03-10	166	g	\N	\N
2151	2026-04-29 12:31:18.22941+00	Coop Pfirsichh├ñlften 240G	1.85	1	0	1.85	Obst und Gemuese	2026-04-13	146	g	\N	\N
2070	2026-04-29 12:19:02.293569+00	isey SKYR nature 170g	2.05	1	0	2.05	Milchprodukte, Eier und Alternativen	2026-04-27	136	g	\N	\N
2058	2026-04-29 12:18:39.660381+00	Living Salad Trio St	1	1	0	1	Obst und Gemuese	2026-04-29	135	stk	\N	\N
2098	2026-04-29 12:19:29.713434+00	Living Salad Trio St	1	1	0	1	Obst und Gemuese	2026-04-23	139	stk	\N	\N
2137	2026-04-29 12:31:18.228305+00	Coop Sbrinz AOP gerieben 2x250g	7.95	1	1.95	6	Milchprodukte, Eier und Alternativen	2026-04-13	146	g	\N	\N
2074	2026-04-29 12:19:02.294094+00	Naturafarm Cervelas 1 Paar	2.8	2	5.6	0	Fleisch, Fisch und pflanzliche Proteine	2026-04-27	136	stk	\N	\N
2181	2026-04-29 12:31:56.821506+00	Coop Sbrinz Port. ca. 300g	7.5	0.29	6.4	0	Milchprodukte, Eier und Alternativen	2026-04-08	149	g	\N	\N
2124	2026-04-29 12:31:01.903396+00	Coop Tortilla Chips Nature 300G	1.65	1	1.65	0	Andere	2026-04-16	145	g	\N	\N
2325	2026-04-29 12:51:23.063167+00	Coop Wienerli 2 Paar 200G	2.8	1	0	2.8	Fleisch, Fisch und pflanzliche Proteine	2026-03-14	161	g	\N	\N
2368	2026-04-29 12:57:24.631746+00	Country Riegel Choco 9x28g	3.95	1	0	3.95	Andere	2026-03-10	166	g	\N	\N
2095	2026-04-29 12:19:29.712909+00	Naturafarm Eier Schweiz 12ST 53g+	6.5	1	1	5.5	Milchprodukte, Eier und Alternativen	2026-04-23	139	stk	\N	\N
2135	2026-04-29 12:31:18.228305+00	Coop Gruy├¿re AOP gerieben 250g	4.95	1	0	4.95	Milchprodukte, Eier und Alternativen	2026-04-13	146	g	\N	\N
2153	2026-04-29 12:31:18.22941+00	Coop MH Mango getrocknet 200G	4.5	1	0	4.5	Andere	2026-04-13	146	g	\N	\N
2380	2026-04-29 12:57:39.84157+00	Barilla Piccolini Pipe Rigate 500g	2.7	1	0	2.7	Andere	2026-03-06	167	g	\N	\N
2331	2026-04-29 12:51:44.323193+00	BB Bio Kuchenteig rund 270G	2.3	1	1.35	0.95	Backwaren und Getreide	2026-03-13	163	g	\N	\N
2057	2026-04-29 12:18:39.660381+00	BB Dinkel Bl├ñtterteig eckig 320G	3.6	1	2.15	1.45	Backwaren und Getreide	2026-04-29	135	g	\N	\N
2092	2026-04-29 12:19:09.367246+00	Naturaplan Bio La Mocca CoffeeMedium 3DL	3.5	1	0	3.5	Getr├ñnke (alkoholisch & alkoholfrei)	2026-04-25	137	dl	\N	\N
2305	2026-04-29 12:41:39.288012+00	Bio Gurken St	1.6	1	1.3	0.3	Obst und Gemuese	2026-03-20	158	stk	\N	\N
2372	2026-04-29 12:57:39.841047+00	Bio Heidelbeeren 200g	4.4	1	0	4.4	Andere	2026-03-06	167	g	\N	\N
2307	2026-04-29 12:41:39.288012+00	Barilla Pesto alla Genovese 190g	4	1	0	4	Gew├╝rze, Kr├ñuter und Saucen	2026-03-20	158	g	\N	\N
2149	2026-04-29 12:31:18.22941+00	Coop Backofen Pommes Duchesse TK 600g	4.3	1	0	4.3	Tiefkuehlprodukte	2026-04-13	146	g	\N	\N
2214	2026-04-29 12:39:24.13308+00	Barilla Pesto Basilico e Mozzarella 190G	4.45	1	0	4.45	Gew├╝rze, Kr├ñuter und Saucen	2026-04-02	152	g	\N	\N
2215	2026-04-29 12:39:24.13308+00	Barilla Pesto Rosso 200G	3.9	1	0	3.9	Gew├╝rze, Kr├ñuter und Saucen	2026-04-02	152	g	\N	\N
2376	2026-04-29 12:57:39.841047+00	Barilla Pesto Rosso 200G	4	1	0	4	Gew├╝rze, Kr├ñuter und Saucen	2026-03-06	167	g	\N	\N
2335	2026-04-29 12:51:44.323717+00	Barilla Pizzasauce 400g	2.95	1	0	2.95	Gew├╝rze, Kr├ñuter und Saucen	2026-03-13	163	g	\N	\N
2375	2026-04-29 12:57:39.841047+00	Barilla Tomatensauce Basilico 400G	3	2	0	6	Gew├╝rze, Kr├ñuter und Saucen	2026-03-06	167	g	\N	\N
2377	2026-04-29 12:57:39.841047+00	Barilla Tomatensauce Napoletana 400G	3	1	0	3	Gew├╝rze, Kr├ñuter und Saucen	2026-03-06	167	g	\N	\N
2088	2026-04-29 12:19:02.295745+00	Naturaplan Bio Schnitzwasser 1L	1.5	1	0	1.5	Andere	2026-04-27	136	l	\N	\N
2129	2026-04-29 12:31:18.228305+00	Bio Vollkorntoast 500G	3.5	1	1.5	2	Backwaren und Getreide	2026-04-13	146	g	\N	\N
2120	2026-04-29 12:31:01.903396+00	Bio Zitronen St	0.5	1	0.5	0	Obst und Gemuese	2026-04-16	145	stk	\N	\N
2097	2026-04-29 12:19:29.713434+00	Bio ├äpfel Gala vv	3.5	0.648	0	2.268	Obst und Gemuese	2026-04-23	139	g	\N	\N
2142	2026-04-29 12:31:18.228886+00	Bio ├äpfel Gala vv	3.1	0.731	0.85	1.4161	Obst und Gemuese	2026-04-13	146	stk	\N	\N
2096	2026-04-29 12:19:29.713434+00	Bio ├äpfel rot vv	5.1	0.81	0	4.131	Obst und Gemuese	2026-04-23	139	stk	\N	\N
2099	2026-04-29 12:19:29.713434+00	Bio ├£nique Gem├╝se Mix TT 1.5kg	2.95	1	0	2.95	Obst und Gemuese	2026-04-23	139	kg	\N	\N
2084	2026-04-29 12:19:02.295227+00	Prix Garantie FSI Petit Beur. Choc. 125G	1.25	1	0	1.25	Andere	2026-04-27	136	g	\N	\N
2121	2026-04-29 12:31:01.903396+00	Bio ├£nique Gem├╝se Mix TT 1.5kg	2.95	1	2.95	0	Obst und Gemuese	2026-04-16	145	stk	\N	\N
2111	2026-04-29 12:25:14.710977+00	Red Bull Energy 25cl	1.5	1	0	1.5	Getr├ñnke (alkoholisch & alkoholfrei)	2026-04-18	142	cl	\N	\N
2089	2026-04-29 12:19:02.295745+00	Red Bull sugar free 250ml	1.5	1	0	1.5	Getr├ñnke (alkoholisch & alkoholfrei)	2026-04-27	136	ml	\N	\N
2437	2026-04-29 15:22:24.381102+00	Butterzopf 320G	2.65	1	0	2.65		2026-04-04	175		\N	\N
2438	2026-04-29 15:22:24.381646+00	Coop Reiswaffeln FT Joghurt gf 100G	1.2	1	0	1.2		2026-04-04	175		\N	\N
2439	2026-04-29 15:22:24.382181+00	Coop Maiswaffeln Quinoa&Amaranth 130G	2.5	1	0	2.5		2026-04-04	175		\N	\N
2440	2026-04-29 15:22:24.382181+00	Coop IPS Halbrahm UHT 250ml	1.6	1	0	1.6		2026-04-04	175		\N	\N
2441	2026-04-29 15:22:24.382181+00	CNp Bio Jogurt Bifidus Natur 500g	1.8	1	0	1.8		2026-04-04	175		\N	\N
2442	2026-04-29 15:22:24.382181+00	Gazi Halloumi Grillk├ñse Natur 250g	4.95	1	0	4.95		2026-04-04	175		\N	\N
2443	2026-04-29 15:22:24.382181+00	Natura-Veal Kalbspl├ñtzli 2-3Stk. ca.180g	10.15	0.156	0	1.5834		2026-04-04	175		\N	\N
2066	2026-04-29 12:19:02.293008+00	Roland Pancroc Vollkorn 125G	2.25	1	0	2.25	Andere	2026-04-27	136	g	\N	\N
2444	2026-04-29 15:22:24.382707+00	Bio S-Hohr├╝ckensteak aufge.ca 300g	11.2	0.298	0	3.3376		2026-04-04	175		\N	\N
2062	2026-04-29 12:18:39.660381+00	SmartStore Hobbybox 14 Liter 3er Set	39.95	1	19.95	20	Andere	2026-04-29	135	l	\N	\N
2445	2026-04-29 15:22:24.382707+00	Max Havelaar Bananen offen PLU 100	1.15	0.444	0	0.5106		2026-04-04	175		\N	\N
2446	2026-04-29 15:22:24.382707+00	Bio Beeren mix 250g	4.15	1	0	4.15		2026-04-04	175		\N	\N
2447	2026-04-29 15:22:24.382707+00	Birnen Conf├®rence 6kg offen 128	0.8	0.324	0	0.2592		2026-04-04	175		\N	\N
2448	2026-04-29 15:22:24.382707+00	Bio Spargeln gr├╝n 500g	7.75	1	0	7.75		2026-04-04	175		\N	\N
2449	2026-04-29 15:22:24.382707+00	Bio Cherry Datterino 350g	2.95	1	0	2.95		2026-04-04	175		\N	\N
2213	2026-04-29 12:39:24.13308+00	Sluups Ginger Shot 60ML	2.8	1	0	2.8	Andere	2026-04-02	152	ml	\N	\N
2450	2026-04-29 15:22:24.383223+00	Bio Kartoffeln gr├╝n 1KG CH	2.9	1	0	2.9		2026-04-04	175		\N	\N
2451	2026-04-29 15:22:24.383223+00	Naturaplan Bio Chips Alpenkr├ñuter 140g	3.5	1	0	3.5		2026-04-04	175		\N	\N
2059	2026-04-29 12:18:39.660381+00	Starbucks Nespresso Blond Espresso 36K.	17.95	2	0	35.9	Andere	2026-04-29	135	k	\N	\N
2104	2026-04-29 12:24:58.622333+00	Starbucks Nespresso Blond Espresso 36K.	17.95	1	0	17.95	Andere	2026-04-22	140	k	\N	\N
2350	2026-04-29 12:57:10.172631+00	conviva Sensitiv+ Pflasterstrips 20ST	2	1	1	1	Andere	2026-03-12	165	stk	\N	\N
2105	2026-04-29 12:24:58.622333+00	Starbucks Nespresso Blond Espresso 36K.	17.95	1	0	17.95	Andere	2026-04-22	140	k	\N	\N
2060	2026-04-29 12:18:39.660381+00	Swiss Alpina gr├╝n 6x1.5L	6.4	1	0	6.4	Andere	2026-04-29	135	l	\N	\N
2103	2026-04-29 12:19:29.713958+00	Appenzeller Bier Qu├Âllfrisch DS 33CL	1.65	1	0.95	0.7	Getr├ñnke (alkoholisch & alkoholfrei)	2026-04-23	139	cl	\N	\N
2061	2026-04-29 12:18:39.660381+00	Swiss Alpina rot 6x1.5L	6.4	1	0	6.4	Andere	2026-04-29	135	l	\N	\N
2106	2026-04-29 12:24:58.622333+00	Swiss Alpina rot 75CL	1	1	0	1	Andere	2026-04-22	140	cl	\N	\N
2071	2026-04-29 12:19:02.293569+00	TAM TAM Vanille 2x4x100g	4.75	1	3.8	0.95	Andere	2026-04-27	136	g	\N	\N
2452	2026-04-29 15:22:32.382724+00	Naturaplan Bio Vollmilch UHT 6x1l	11.7	1	9.95	1.75		2026-04-04	176		\N	\N
2453	2026-04-29 15:22:32.383241+00	Bio Max Havelaar Bananen offen 101	1.8	0.566	0	1.0188		2026-04-04	176		\N	\N
2454	2026-04-29 15:22:32.383241+00	Zwiebeln rot IP 500g	1.2	1	0	1.2		2026-04-04	176		\N	\N
2455	2026-04-29 15:22:32.383241+00	Naturaplan Bio Fusilli Emmer 400g	3.4	1	0	3.4		2026-04-04	176		\N	\N
2456	2026-04-29 15:22:32.383241+00	Milupa Kinderm├╝sli Fr├╝chte 400G	9.5	1	0	9.5		2026-04-04	176		\N	\N
2082	2026-04-29 12:19:02.295227+00	Auberginen offen 167	1.65	0.338	1.65	0	Obst und Gemuese	2026-04-27	136	kg	\N	\N
2457	2026-04-29 15:22:45.859664+00	Rustico Flute Tomate Mozzarella HG 300G	7.4	1	0	7.4		2026-04-01	177		\N	\N
2458	2026-04-29 15:22:45.859664+00	Butterweggli 70G	0.75	1	0	0.75		2026-04-01	177		\N	\N
2459	2026-04-29 15:22:45.860195+00	Bio Max Havelaar Bananen offen 101	1.05	0.334	0	0.3507		2026-04-01	177		\N	\N
2065	2026-04-29 12:19:02.293008+00	BB Marmor Cake 110G	2.2	1	0	2.2	Andere	2026-04-27	136	g	\N	\N
2460	2026-04-29 15:22:45.860195+00	Bio ├äpfel Braeburn offen 320	1.55	0.244	0	0.3782		2026-04-01	177		\N	\N
2083	2026-04-29 12:19:02.295227+00	Bio Kr├ñuterseitling offen PLU 408	3.8	0.128	3.8	0	Obst und Gemuese	2026-04-27	136	kg	\N	\N
2076	2026-04-29 12:19:02.294661+00	Bio Max Havelaar Bananen offen 101	1.8	0.57	1.8	0	Obst und Gemuese	2026-04-27	136	kg	\N	\N
2461	2026-04-29 15:22:45.860195+00	Bio Mango st	3.25	1	0	3.25		2026-04-01	177		\N	\N
2462	2026-04-29 15:22:45.860195+00	Bio ├£nique Gem├╝se Mix TT 1.5kg	2.95	1	0	2.95		2026-04-01	177		\N	\N
2463	2026-04-29 15:22:45.860195+00	Bio MH Schokoladenpulver 250g	4.95	1	0	4.95		2026-04-01	177		\N	\N
2464	2026-04-29 15:22:45.860195+00	familia C.M. plus 2x600	11.9	1	9.5	2.4		2026-04-01	177		\N	\N
2465	2026-04-29 15:22:45.860195+00	Halba Tafel Cr├®mant 200G	2.95	1	0	2.95		2026-04-01	177		\N	\N
2466	2026-04-29 15:22:45.860195+00	Smarties Riesenrolle 130G	3.2	1	0	3.2		2026-04-01	177		\N	\N
2467	2026-04-29 15:22:45.860787+00	Smarties Mini 216G	4.3	1	0	4.3		2026-04-01	177		\N	\N
2468	2026-04-29 15:22:45.860787+00	Kinder Harry Hase mini 3x15g	2.95	1	0	2.95		2026-04-01	177		\N	\N
2469	2026-04-29 15:22:45.860787+00	Naturaplan Bio Schnitzwasser 50CL	1	1	0	1		2026-04-01	177		\N	\N
2470	2026-04-29 15:22:45.860787+00	Red Bull sugar free 250ml	1.5	2	0	3		2026-04-01	177		\N	\N
2080	2026-04-29 12:19:02.295227+00	Bio Peperoni Palermo 240g	2.95	1	0	2.95	Obst und Gemuese	2026-04-27	136	g	\N	\N
2073	2026-04-29 12:19:02.294094+00	Bio Pouletfl├╝geli 5 St. ca.335g	8	0.381	7.05	0	Fleisch, Fisch und pflanzliche Proteine	2026-04-27	136	kg	\N	\N
2471	2026-04-29 15:22:45.860787+00	Red Bull Energy 25cl	1.5	1	0	1.5		2026-04-01	177		\N	\N
2160	2026-04-29 12:31:29.230408+00	Butterweggli 70G	0.75	1	0	0.75	Backwaren und Getreide	2026-04-10	147	g	\N	\N
2472	2026-04-29 15:22:45.860787+00	Elmex Kinder Zahnpaste 75ML	4.9	1	4.9	0		2026-04-01	177		\N	\N
2473	2026-04-29 15:22:45.860787+00	Garnier Micellar All-In-One 400ML	7.95	1	7.95	0		2026-04-01	177		\N	\N
2474	2026-04-29 15:22:45.860787+00	Garnier Pimple Patch Ultra 22ST	11.95	1	11.95	0		2026-04-01	177		\N	\N
2300	2026-04-29 12:41:39.288012+00	Bio ├äpfel Gala offen PLU 159	1.8	0.372	0	0.6696	Obst und Gemuese	2026-03-20	158	kg	\N	\N
2475	2026-04-29 15:22:45.861318+00	MNY Sunkisser Blush 06 SUNSET	15.95	1	0	15.95		2026-04-01	177		\N	\N
2476	2026-04-29 15:22:45.861318+00	MNY MASCARA LASH SENSATIONAL SKY HIG	19.95	0	19.95	0		2026-04-01	177		\N	\N
2477	2026-04-29 15:22:45.861318+00	Stimorol Spearmint 7x14g (98g)	4.95	1	0	4.95		2026-04-01	177		\N	\N
2478	2026-04-29 15:22:45.861318+00	Halsfeger Kr├ñuterbonbon 90G	2.5	1	0	2.5		2026-04-01	177		\N	\N
2479	2026-04-29 15:22:45.861318+00	Kik Nature Zeckenschutz 100ML	11.5	1	5.75	5.75		2026-04-01	177		\N	\N
2167	2026-04-29 12:31:37.745747+00	Butterweggli 70G	0.75	1	0	0.75	Backwaren und Getreide	2026-04-09	148	g	\N	\N
2262	2026-04-29 12:41:12.289335+00	Birnen Kaiser IP 12.5kg offen PLU 267	1.9	0.532	0	1.0108	Obst und Gemuese	2026-03-25	156	kg	\N	\N
2257	2026-04-29 12:41:12.289335+00	Butterweggli 70G	0.75	1	0	0.75	Backwaren und Getreide	2026-03-25	156	g	\N	\N
2283	2026-04-29 12:41:24.764053+00	Clean Holzstiel FSC	5.6	1	0	5.6	Reinigungsmittel und Haushaltsreiniger	2026-03-20	157	stk	\N	\N
2284	2026-04-29 12:41:24.764053+00	Clean Schrubber FSC ohne Stiel	10.95	1	0	10.95	Reinigungsmittel und Haushaltsreiniger	2026-03-20	157	stk	\N	\N
2480	2026-04-29 15:22:56.714057+00	Flasche	0.5	1	0	0.5		2026-02-28	178		\N	\N
2481	2026-04-29 15:22:56.71461+00	Prix Garantie Kochbutter 250g	3.4	1	0	3.4		2026-02-28	178		\N	\N
2391	2026-04-29 12:57:39.842092+00	conviva Thermometer digital flex. Spitze	9.8	1	0	9.8	Andere	2026-03-06	167	stk	\N	\N
2392	2026-04-29 12:57:39.842092+00	conviva Thermometer digital flex. Spitze	9.8	0	-9.8	9.8	Andere	2026-03-06	167	stk	\N	\N
2482	2026-04-29 15:22:56.71461+00	Coop Eier Freiland Schweiz 10St 53g+	5.35	1	0	5.35		2026-02-28	178		\N	\N
2483	2026-04-29 15:22:56.71461+00	Prix Garantie Pesto Verde 190G	1.35	1	0	1.35		2026-02-28	178		\N	\N
2484	2026-04-29 15:22:56.715179+00	Bio 365 Sugo Basilico 400G	2.1	1	0	2.1		2026-02-28	178		\N	\N
2260	2026-04-29 12:41:12.289335+00	Coop IPS Milchdrink UHT 1.5% 6x1L Edge	9.6	2	0	19.2	Milchprodukte, Eier und Alternativen	2026-03-25	156	l	\N	\N
2485	2026-04-29 15:22:56.715179+00	Naturaplan Bio Halbweissmehl 1KG	3.2	1	0	3.2		2026-02-28	178		\N	\N
2486	2026-04-29 15:22:56.715179+00	Coop Weissmehl IP Suisse 1KG	1.9	1	0	1.9		2026-02-28	178		\N	\N
2487	2026-04-29 15:22:56.715179+00	Coop Weissmehl IP Suisse 1KG	1.9	0	0	0		2026-02-28	178		\N	\N
2488	2026-04-29 15:22:56.715723+00	Burgdorfer Bier Weizen 50CL	2.5	1	1.5	1		2026-02-28	178		\N	\N
2489	2026-04-29 15:22:56.715723+00	Burgdorfer Bier Weizen 50CL	2.5	1	0	2.5		2026-02-28	178		\N	\N
2490	2026-04-29 15:22:56.715723+00	Burgdorfer Bier Weizen 50CL	2.5	0	0	0		2026-02-28	178		\N	\N
2275	2026-04-29 12:41:12.289856+00	Country Riegel Apple 8x25g	3.8	1	0	3.8	Andere	2026-03-25	156	g	\N	\N
2126	2026-04-29 12:31:01.903396+00	Feldschl├Âsschen Helvetic Dose 33CL	1.75	2	3.5	0	Getr├ñnke (alkoholisch & alkoholfrei)	2026-04-16	145	cl	\N	\N
2128	2026-04-29 12:31:18.227679+00	Hot Chili 15G	2.4	1	0	2.4	Gew├╝rze, Kr├ñuter und Saucen	2026-04-13	146	g	\N	\N
2136	2026-04-29 12:31:18.228305+00	Coop Gruy├¿re AOP gerieben 250g	4.95	0	0	0	Milchprodukte, Eier und Alternativen	2026-04-13	146	g	\N	\N
2491	2026-04-29 15:23:11.440426+00	Butterweggli 70G	0.75	1	0	0.75		2026-02-27	179		\N	\N
2492	2026-04-29 15:23:11.440988+00	Naturaplan Bio Vollmilch UHT 6x1l	11.7	1	9.95	1.75		2026-02-27	179		\N	\N
2493	2026-04-29 15:23:11.440988+00	CNp Bio Jogurt 3.8% Bifidus Natur 4x125g	2.7	1	0	2.7		2026-02-27	179		\N	\N
2494	2026-04-29 15:23:11.440988+00	Bio Avocado St	2.15	1	0	2.15		2026-02-27	179		\N	\N
2495	2026-04-29 15:23:11.440988+00	Bio Karotten 1kg CH	3	1	0	3		2026-02-27	179		\N	\N
2496	2026-04-29 15:23:11.440988+00	Bio Peperoni 500g	3.2	1	0	3.2		2026-02-27	179		\N	\N
2497	2026-04-29 15:23:11.440988+00	Bio Kartoffeln gr├╝n 1KG CH	2.9	1	0	2.9		2026-02-27	179		\N	\N
2498	2026-04-29 15:23:11.441534+00	Naturaplan Bio Schnitzwasser 50CL	1	1	0	1		2026-02-27	179		\N	\N
2499	2026-04-29 15:23:11.441534+00	Pampers Harmonie Aqua 4x48ST	13.95	1	13.95	0		2026-02-27	179		\N	\N
2500	2026-04-29 15:23:11.441534+00	Prix Garantie Topa classic 10ROL	3.75	1	3.75	0		2026-02-27	179		\N	\N
2138	2026-04-29 12:31:18.228886+00	Coop Gruy├¿re Schmelzk├ñsescheiben 200g	2.95	1	0	2.95	Milchprodukte, Eier und Alternativen	2026-04-13	146	g	\N	\N
2501	2026-04-29 15:23:11.441534+00	Tempo Premium 4-lagig 24ROL	26.5	1	26.5	0		2026-02-27	179		\N	\N
2140	2026-04-29 12:31:18.228886+00	Coop Hobelfleisch extra fein 94G	7.5	1	0	7.5	Fleisch, Fisch und pflanzliche Proteine	2026-04-13	146	g	\N	\N
2502	2026-04-29 15:23:11.441534+00	Smoby Dreirad Be Move Komfort Beige	79.95	1	79.95	0		2026-02-27	179		\N	\N
2131	2026-04-29 12:31:18.228305+00	Coop Maiswaffeln Quinoa&Amaranth 130G	2.5	1	0	2.5	Snacks, Apero und Suesswaren	2026-04-13	146	g	\N	\N
2130	2026-04-29 12:31:18.228305+00	DAR-VIDA Choco noisette 3Po 138G	4.95	1	0	4.95	Snacks, Apero und Suesswaren	2026-04-13	146	g	\N	\N
2133	2026-04-29 12:31:18.228305+00	Die Butter M├Âdeli 250G	3.85	2	0	7.7	Milchprodukte, Eier und Alternativen	2026-04-13	146	g	\N	\N
2118	2026-04-29 12:25:33.27516+00	Einzahlung Lotto/Lose	10	1	0	10	Andere	2026-04-16	144	stk	\N	\N
2166	2026-04-29 12:31:29.230977+00	Gratis Bio Kartoffeln gr├╝n CH	-2.9	1	0	0	Obst und Gemuese	2026-04-10	147	kg	\N	\N
2123	2026-04-29 12:31:01.903396+00	Halba Tafel Cr├®mant 200G	2.95	1	2.95	0	Andere	2026-04-16	145	g	\N	\N
2117	2026-04-29 12:25:33.27516+00	Havelaar Rosen 20ST 40cm Co7	9.95	1	0	9.95	Andere	2026-04-16	144	stk	\N	\N
2156	2026-04-29 12:31:18.22941+00	Hero Triangoli 420g	5.95	1	0	5.95	Konserven und Vorratsartikel	2026-04-13	146	g	\N	\N
2116	2026-04-29 12:25:24.286975+00	JaMaDu Riegel Apfel-Karotte-Mango 6x24g	3.5	1	0	3.5	Snacks, Apero und Suesswaren	2026-04-18	143	g	\N	\N
2161	2026-04-29 12:31:29.230408+00	Karma Pita Bread 6Stk 400G	2.4	1	0	2.4	Backwaren und Getreide	2026-04-10	147	g	\N	\N
2144	2026-04-29 12:31:18.228886+00	Karotten IP offen PLU 327	0.6	0.382	0	0.2292	Obst und Gemuese	2026-04-13	146	kg	\N	\N
2155	2026-04-29 12:31:18.22941+00	Red Bull sugar free 250ml	1.5	1	0	1.5	Getr├ñnke (alkoholisch & alkoholfrei)	2026-04-13	146	ml	\N	\N
2143	2026-04-29 12:31:18.228886+00	Lauch gr├╝n offen 195	1.3	0.302	0	0.3926	Obst und Gemuese	2026-04-13	146	g	\N	\N
2169	2026-04-29 12:31:37.745747+00	Laugengipfel mit Kernen 70G	1.3	1	0	1.3	Backwaren und Getreide	2026-04-09	148	g	\N	\N
2139	2026-04-29 12:31:18.228886+00	Naturafarm Cervelas 1 Paar	2.8	1	0	2.8	Fleisch, Fisch und pflanzliche Proteine	2026-04-13	146	stk	\N	\N
2346	2026-04-29 12:57:10.172078+00	Halba Dino Zora Triceratops 220G	9.5	1	0	9.5	Andere	2026-03-12	165	g	\N	\N
2347	2026-04-29 12:57:10.172078+00	Halba Entchen Emil 160G	7.95	1	0	7.95	Andere	2026-03-12	165	g	\N	\N
2344	2026-04-29 12:57:10.172078+00	Halba Hase Himby 60G	3.95	1	0	3.95	Andere	2026-03-12	165	g	\N	\N
2345	2026-04-29 12:57:10.172078+00	Halba Hase Honig-Nougat weiss 140G	5.95	1	0	5.95	Andere	2026-03-12	165	g	\N	\N
2343	2026-04-29 12:57:10.171537+00	Halba Sitzhase Milch 40G	1.95	1	0	1.95	Andere	2026-03-12	165	g	\N	\N
2158	2026-04-29 12:31:18.22941+00	Naturaplan Bio Riegel Muesli 6x25g	4.7	1	0	4.7	Snacks, Apero und Suesswaren	2026-04-13	146	g	\N	\N
2127	2026-04-29 12:31:18.22716+00	Naturaplan Bio Tortelli Ric./Spi. 2x500g	11.1	1	2.8	8.3	Andere	2026-04-13	146	g	\N	\N
2145	2026-04-29 12:31:18.228886+00	Peperoni farbig 700g	2	1	0	2	Obst und Gemuese	2026-04-13	146	g	\N	\N
2148	2026-04-29 12:31:18.228886+00	Primagusto Tomaten Cherry Rispen 300g	3.95	1	1	2.95	Obst und Gemuese	2026-04-13	146	g	\N	\N
2159	2026-04-29 12:31:29.230408+00	Prix Garantie Gnocchi 600G	1.7	1	0	1.7	Andere	2026-04-10	147	g	\N	\N
2147	2026-04-29 12:31:18.228886+00	Prix Garantie Zwiebeln Bund	1.7	1	0	1.7	Andere	2026-04-13	146	stk	\N	\N
2152	2026-04-29 12:31:18.22941+00	Sapori Fusilli Bucati 3x500g	5	1	2.5	2.5	Andere	2026-04-13	146	g	\N	\N
2146	2026-04-29 12:31:18.228886+00	Spargelspitzen gr├╝n 300g	4.45	1	1.95	2.5	Obst und Gemuese	2026-04-13	146	g	\N	\N
2157	2026-04-29 12:31:18.22941+00	Stimorol Original 7x14g (98g)	4.95	1	0	4.95	Snacks, Apero und Suesswaren	2026-04-13	146	g	\N	\N
2163	2026-04-29 12:31:29.230977+00	S├╝sskartoffeln Batati CH offen 109	2.05	0.298	0	0.6109	Obst und Gemuese	2026-04-10	147	g	\N	\N
2119	2026-04-29 12:31:01.903396+00	Urdinkelbrot artisanal IPS 450G	4.2	1	3.2	1	Backwaren und Getreide	2026-04-16	145	g	\N	\N
2125	2026-04-29 12:31:01.903396+00	Valaisanne Lager Dose 50CL	2.3	2	4.6	0	Andere	2026-04-16	145	cl	\N	\N
2164	2026-04-29 12:31:29.230977+00	Bio Kartoffeln gr├╝n 1KG CH	2.9	1	0	2.9	Obst und Gemuese	2026-04-10	147	kg	\N	\N
2113	2026-04-29 12:25:24.286432+00	Bio Landbr├Âtli 90G	1.3	1	0	1.3	Obst und Gemuese	2026-04-18	143	g	\N	\N
2162	2026-04-29 12:31:29.230408+00	Champignons weiss 300g	2.9	1	0	2.9	Obst und Gemuese	2026-04-10	147	g	\N	\N
2154	2026-04-29 12:31:18.22941+00	Coop Apfelschnitze getrocknet 200G	3.5	1	0	3.5	Andere	2026-04-13	146	g	\N	\N
2185	2026-04-29 12:31:56.822026+00	Bio ├£nique Gem├╝se Mix TT 1.5kg	2.95	1	0	2.95	Obst und Gemuese	2026-04-08	149	kg	\N	\N
2276	2026-04-29 12:41:12.289856+00	Country Riegel Choco Coconut 8x30g	3.95	1	0	3.95	Andere	2026-03-25	156	g	\N	\N
2265	2026-04-29 12:41:12.289335+00	Hipp Milchbrei Kindergriess 250g	5.45	1	0	5.45	Milchprodukte, Eier und Alternativen	2026-03-25	156	g	\N	\N
2258	2026-04-29 12:41:12.289335+00	Laugengipfel mit Kernen 70G	1.3	1	0	1.3	Backwaren und Getreide	2026-03-25	156	g	\N	\N
2263	2026-04-29 12:41:12.289335+00	Max Havelaar Papaya St (7St)	3.6	1	0	3.6	Obst und Gemuese	2026-03-25	156	stk	\N	\N
2192	2026-04-29 12:31:56.822026+00	Pl├╝sch Raupe	19.9	1	1	18.9	Andere	2026-04-08	149	stk	\N	\N
2336	2026-04-29 12:51:44.323717+00	Red Bull sugar free 250ml	1.5	1	0	1.5	Getr├ñnke (alkoholisch & alkoholfrei)	2026-03-13	163	ml	\N	\N
2311	2026-04-29 12:41:39.288012+00	Red Bull Zero 25CL	1.5	1	0	1.5	Getr├ñnke (alkoholisch & alkoholfrei)	2026-03-20	158	cl	\N	\N
2079	2026-04-29 12:19:02.294661+00	Primagusto Spargeln weiss 750g	12.95	1	9.5	3.45	Obst und Gemuese	2026-04-27	136	g	\N	\N
2291	2026-04-29 12:41:39.288012+00	R&L Mega Buns Rustico 330G	2.95	1	0	2.95	Andere	2026-03-20	158	g	\N	\N
2285	2026-04-29 12:41:24.764053+00	Unicorn Dartboard Papier Board	29.95	1	10	19.95	Andere	2026-03-20	157	stk	\N	\N
2107	2026-04-29 12:25:06.653088+00	Urdinkelbrot artisanal IPS 450G	4.2	1	3.2	1	Backwaren und Getreide	2026-04-22	141	g	\N	\N
2090	2026-04-29 12:19:02.296317+00	V6 White Spearmint Beutel 91G	5.95	1	0	5.95	Andere	2026-04-27	136	g	\N	\N
2102	2026-04-29 12:19:29.713958+00	Valaisanne Lager Dose 50CL	2.3	2	1	3.6	Andere	2026-04-23	139	cl	\N	\N
2110	2026-04-29 12:25:14.710977+00	Valser Prickelnd 50CL	1	1	0	1	Andere	2026-04-18	142	cl	\N	\N
2112	2026-04-29 12:25:24.286432+00	VG St.Galler Ruchbrot 500G	2.5	1	0	2.5	Andere	2026-04-18	143	g	\N	\N
2289	2026-04-29 12:41:39.287433+00	VG St.Galler Ruchbrot 500G	2.5	1	0	2.5	Andere	2026-03-20	158	g	\N	\N
2191	2026-04-29 12:31:56.822026+00	Evian Mineralwasser mit Kohlens├ñure	1.1	1	0.95	0.15	Getr├ñnke (alkoholisch & alkoholfrei)	2026-04-08	149	l	\N	\N
2221	2026-04-29 12:39:24.133673+00	Focus Water Active 50CL	2.1	1	0	2.1	Getr├ñnke (alkoholisch & alkoholfrei)	2026-04-02	152	cl	\N	\N
2172	2026-04-29 12:31:37.745747+00	Vitamin Well Reload 50CL	2.25	1	0	2.25	Getr├ñnke (alkoholisch & alkoholfrei)	2026-04-09	148	cl	\N	\N
2180	2026-04-29 12:31:56.821506+00	Coop Grana Padano DOP 3/4fett ca. 270G	6.4	0.28	0	1.792	Milchprodukte, Eier und Alternativen	2026-04-08	149	g	\N	\N
2176	2026-04-29 12:31:56.821506+00	Coop IPS Halbrahm UHT 250ml	1.6	1	0	1.6	Milchprodukte, Eier und Alternativen	2026-04-08	149	ml	\N	\N
2178	2026-04-29 12:31:56.821506+00	Coop IPS Saucen Halbrahm 200ml	2.15	1	0	2.15	Milchprodukte, Eier und Alternativen	2026-04-08	149	ml	\N	\N
2177	2026-04-29 12:31:56.821506+00	Coop IPS Saurer Halbrahm 200g	1.75	1	0	1.75	Milchprodukte, Eier und Alternativen	2026-04-08	149	g	\N	\N
2190	2026-04-29 12:31:56.822026+00	Halba H├ñsli Honig-Nougat weiss 60G	3.95	1	1.95	2	Andere	2026-04-08	149	g	\N	\N
2175	2026-04-29 12:31:56.821506+00	HB Bio Zopfbr├Âtli 80G	0.95	1	0	0.95	Backwaren und Getreide	2026-04-08	149	g	\N	\N
2183	2026-04-29 12:31:56.821506+00	Living Eichblattsalat rot St	1.95	1	0	1.95	Obst und Gemuese	2026-04-08	149	stk	\N	\N
2220	2026-04-29 12:39:24.133673+00	Mastro Lorenzo Bohnenkaffee 1KG	22.95	1	0	22.95	Andere	2026-04-02	152	kg	\N	\N
2216	2026-04-29 12:39:24.13308+00	Naturaplan Bio Halbweissmehl 1KG	3.2	1	0	3.2	Backwaren und Getreide	2026-04-02	152	kg	\N	\N
2186	2026-04-29 12:31:56.822026+00	Naturaplan Bio R├Âsti fixfertig 500G	3.3	1	0	3.3	Andere	2026-04-08	149	g	\N	\N
2219	2026-04-29 12:39:24.13308+00	Prix Garantie Backpulver 10x15G	0.5	1	0	0.5	Andere	2026-04-02	152	g	\N	\N
2184	2026-04-29 12:31:56.822026+00	Prix Garantie Eisberg 12St	1	1	0	1	Andere	2026-04-08	149	stk	\N	\N
2217	2026-04-29 12:39:24.13308+00	Prix Garantie Mandeln gemahlen 200G	1.1	1	0	1.1	Andere	2026-04-02	152	g	\N	\N
2189	2026-04-29 12:31:56.822026+00	Starbucks Nespresso Blond Espresso 36K.	17.95	1	0	17.95	Andere	2026-04-08	149	k	\N	\N
2188	2026-04-29 12:31:56.822026+00	Starbucks Nespresso Caramel 10Kap.	5.95	1	0	5.95	Andere	2026-04-08	149	kap	\N	\N
2174	2026-04-29 12:31:56.821506+00	VG St.Galler Ruchbrot 500G	2.5	1	0	2.5	Andere	2026-04-08	149	g	\N	\N
2173	2026-04-29 12:31:37.745747+00	Vitamin Well Awake 50CL	2.25	1	0	2.25	Andere	2026-04-09	148	cl	\N	\N
2122	2026-04-29 12:31:01.903396+00	Coop Churros mit Zucker 250g	4.95	1	4.95	0	Snacks, Apero und Suesswaren	2026-04-16	145	g	\N	\N
2150	2026-04-29 12:31:18.22941+00	Coop Ch├ñs-Ch├╝echli TK 12x70g	8.25	1	0	8.25	Snacks, Apero und Suesswaren	2026-04-13	146	g	\N	\N
2114	2026-04-29 12:25:24.286432+00	Coop Eier Freiland Schweiz 10St 53g+	5.35	1	0	5.35	Milchprodukte, Eier und Alternativen	2026-04-18	143	stk	\N	\N
2280	2026-04-29 12:41:24.764053+00	Mein Emmental Goud 4x33CL	13.2	1	0	13.2	Getr├ñnke (alkoholisch & alkoholfrei)	2026-03-20	157	cl	\N	\N
2251	2026-04-29 12:40:00.821232+00	Red Bull sugar free 250ml	1.5	1	0	1.5	Getr├ñnke (alkoholisch & alkoholfrei)	2026-03-27	154	ml	\N	\N
2266	2026-04-29 12:41:12.289335+00	Red Bull sugar free 250ml	1.5	1	0	1.5	Getr├ñnke (alkoholisch & alkoholfrei)	2026-03-25	156	ml	\N	\N
2254	2026-04-29 12:40:56.870544+00	Starbucks Caramel-Macchiato 220ml	2.45	1	0	2.45	Getr├ñnke (alkoholisch & alkoholfrei)	2026-03-26	155	ml	\N	\N
2250	2026-04-29 12:40:00.821232+00	Zwiebelschalen 85g	1.95	1	0	1.95	Gew├╝rze, Kr├ñuter und Saucen	2026-03-27	154	g	\N	\N
2182	2026-04-29 12:31:56.821506+00	Bio Mango st	3.25	1	0	3.25	Obst und Gemuese	2026-04-08	149	stk	\N	\N
2259	2026-04-29 12:41:12.289335+00	Naturaplan Bio Vollmilch UHT 6x1l	11.7	1	0	11.7	Andere	2026-03-25	156	l	\N	\N
2273	2026-04-29 12:41:12.289335+00	Prix Garantie Kosmetikt├╝cher 200ST	1	1	1	0	Andere	2026-03-25	156	stk	\N	\N
2252	2026-04-29 12:40:00.821232+00	Prix Garantie Strh. Box noir one size	3.1	1	1	2.1	Andere	2026-03-27	154	stk	\N	\N
2256	2026-04-29 12:40:56.870544+00	Rio mare Messicana Thunfischsalat 160G	3.8	1	0	3.8	Andere	2026-03-26	155	g	\N	\N
2269	2026-04-29 12:41:12.289335+00	Sibonet Fl├╝ssigseife Refill 500ML	6.95	1	0	6.95	Andere	2026-03-25	156	ml	\N	\N
2271	2026-04-29 12:41:12.289335+00	Sibonet Fl├╝ssigseife Refill 500ML	6.95	0	0	0	Andere	2026-03-25	156	stk	\N	\N
2274	2026-04-29 12:41:12.289856+00	Super Soft Sensation 3-lagig 32ROL	26.5	1	15.9	10.6	Andere	2026-03-25	156	stk	\N	\N
2264	2026-04-29 12:41:12.289335+00	Zweifel Joujoux Paprika 42g	1.55	1	1	0.55	Snacks, Apero und Suesswaren	2026-03-25	156	g	\N	\N
2247	2026-04-29 12:40:00.821232+00	Bio Max Havelaar Bananen offen	1.15	0.362	0	0.4163	Obst und Gemuese	2026-03-27	154	kg	\N	\N
2277	2026-04-29 12:41:24.763495+00	Bio Spargeln gr├╝n 7x500g	13.95	1	10.95	3	Obst und Gemuese	2026-03-20	157	g	\N	\N
2261	2026-04-29 12:41:12.289335+00	Bio ├äpfel Gala offen PLU 159	1.7	0.342	0	0.5814	Obst und Gemuese	2026-03-25	156	kg	\N	\N
2299	2026-04-29 12:41:39.288012+00	Bio Max Havelaar Bananen offen 101	1.35	0.426	0	0.5751	Obst und Gemuese	2026-03-20	158	kg	\N	\N
2333	2026-04-29 12:51:44.323717+00	Bio Max Havelaar Bananen offen 101	1.9	0.588	0	1.1172	Obst und Gemuese	2026-03-13	163	kg	\N	\N
2301	2026-04-29 12:41:39.288012+00	Birnen Kaiser IP 12.5kg offen PLU 267	1.2	0.328	0	0.3936	Obst und Gemuese	2026-03-20	158	kg	\N	\N
2290	2026-04-29 12:41:39.288012+00	Butterweggli 70G	0.75	1	0	0.75	Backwaren und Getreide	2026-03-20	158	stk	\N	\N
2268	2026-04-29 12:41:12.289335+00	well Seife Almond&Honey Refill 500ML	3.25	1	0	3.25	Andere	2026-03-25	156	ml	\N	\N
2272	2026-04-29 12:41:12.289335+00	Well Sensitive Fl.Seife Ref. 2x500	9.9	1	7.4	2.5	Andere	2026-03-25	156	stk	\N	\N
2270	2026-04-29 12:41:12.289335+00	well Seife Almond&Honey Refill 500ML	3.25	0	0	0	Andere	2026-03-25	156	stk	\N	\N
2317	2026-04-29 12:51:13.706265+00	Butterweggli 70G	0.75	1	0	0.75	Backwaren und Getreide	2026-03-18	160	stk	\N	\N
2296	2026-04-29 12:41:39.288012+00	CNp Bio Jogurt 3.8% Bifidus Natur 4x125g	2.7	1	0	2.7	Milchprodukte, Eier und Alternativen	2026-03-20	158	stk	\N	\N
2322	2026-04-29 12:51:23.06263+00	Coop Eier Freiland Bern 6St 53g+	4.2	0	0	0	Milchprodukte, Eier und Alternativen	2026-03-14	161	stk	\N	\N
2323	2026-04-29 12:51:23.06263+00	Coop Eier Freiland Bern 6St 53g+	4.2	1	0	4.2	Milchprodukte, Eier und Alternativen	2026-03-14	161	stk	\N	\N
2297	2026-04-29 12:41:39.288012+00	Coop Gruy├¿re AOP gerieben 250g	4.95	1	0	4.95	Milchprodukte, Eier und Alternativen	2026-03-20	158	g	\N	\N
2294	2026-04-29 12:41:39.288012+00	Coop IPS Cr├¿me Fra├«che Nature 200g	2.9	1	0	2.9	Milchprodukte, Eier und Alternativen	2026-03-20	158	g	\N	\N
2295	2026-04-29 12:41:39.288012+00	Coop IPS Halbrahm UHT 500ml	2.9	1	0	2.9	Milchprodukte, Eier und Alternativen	2026-03-20	158	ml	\N	\N
2298	2026-04-29 12:41:39.288012+00	Coop weisse Eier Freiland CH 15St 53g+	8	1	0	8	Milchprodukte, Eier und Alternativen	2026-03-20	158	stk	\N	\N
2308	2026-04-29 12:41:39.288012+00	Freche Freunde Keks Dinkel,Erdbee 100g	3.9	1	2.3	1.6	Andere	2026-03-20	158	g	\N	\N
2315	2026-04-29 12:41:39.288585+00	JaMaDu Riegel Apfel-Karotte-Mango 6x24g	3.5	1	0	3.5	Snacks, Apero und Suesswaren	2026-03-20	158	g	\N	\N
2324	2026-04-29 12:51:23.06263+00	Naturafarm Eier Schweiz 6ST 53g+	3.95	1	0	3.95	Milchprodukte, Eier und Alternativen	2026-03-14	161	stk	\N	\N
2318	2026-04-29 12:51:13.706791+00	Naturaplan Bio Schnitzwasser 50CL	1	1	0	1	Andere	2026-03-18	160	cl	\N	\N
2286	2026-04-29 12:41:24.764053+00	Osterkorb rund klein braun	1.95	1	0	1.95	Andere	2026-03-20	157	stk	\N	\N
2313	2026-04-29 12:41:39.288585+00	Prix Garantie Cat Pute+Huhn 4x100g	1.15	2	0	2.3	Tierbedarf und Sonstiges	2026-03-20	158	g	\N	\N
2312	2026-04-29 12:41:39.288585+00	Prix Garantie Cat Rind+Kalb 4x100g	1.15	1	0	1.15	Tierbedarf und Sonstiges	2026-03-20	158	g	\N	\N
2320	2026-04-29 12:51:23.062058+00	Prix Garantie Hot Dog Buns 240G	1.6	1	0	1.6	Andere	2026-03-14	161	g	\N	\N
2332	2026-04-29 12:51:44.323193+00	Prix Garantie Kochbutter 250g	3.4	2	0	6.8	Andere	2026-03-13	163	g	\N	\N
2321	2026-04-29 12:51:23.06263+00	Q&P IPS Milchdrink UHT 1.5%	2.6	1	0	2.6	Andere	2026-03-14	161	l	\N	\N
2288	2026-04-29 12:41:24.764053+00	SPAR-BON	-5.75	1	0	0	Andere	2026-03-20	157	stk	\N	\N
2326	2026-04-29 12:51:23.063167+00	Starbucks Nespresso Blond Espresso 36K.	17.95	1	0	17.95	Andere	2026-03-14	161	stk	\N	\N
2341	2026-04-29 12:51:52.848529+00	Starbucks Nespresso Blond Espresso 36K.	17.95	1	0	17.95	Andere	2026-03-12	164	stk	\N	\N
2339	2026-04-29 12:51:52.848529+00	Starbucks Nespresso Caramel 10Kap.	5.95	1	0	5.95	Andere	2026-03-12	164	kap	\N	\N
2340	2026-04-29 12:51:52.848529+00	Starbucks Nespresso Caramel 10Kap.	5.95	1	0	5.95	Andere	2026-03-12	164	kap	\N	\N
2327	2026-04-29 12:51:23.063167+00	Starbucks Nespresso Vanilla 10Kap.	5.95	1	0	5.95	Andere	2026-03-14	161	kap	\N	\N
2314	2026-04-29 12:41:39.288585+00	Stimorol Spearmint 7x14g (98g)	4.95	1	0	4.95	Snacks, Apero und Suesswaren	2026-03-20	158	g	\N	\N
2337	2026-04-29 12:51:44.323717+00	Vorratsbeh├ñlter	14.9	1	0	14.9	Konserven und Vorratsartikel	2026-03-13	163	stk	\N	\N
2319	2026-04-29 12:51:23.062058+00	Weinl├ñnderbrot 250G	2.5	1	0	2.5	Backwaren und Getreide	2026-03-14	161	g	\N	\N
2334	2026-04-29 12:51:44.323717+00	Zwiebeln rot IP 500g	1.2	1	0	1.2	Obst und Gemuese	2026-03-13	163	g	\N	\N
2287	2026-04-29 12:41:24.764053+00	Babygarn Bambi 100g	8.4	1	0	8.4	Andere	2026-03-20	157	g	\N	\N
2303	2026-04-29 12:41:39.288012+00	Bio Broccoli offen PLU 654	1.9	0.43	0	0.817	Obst und Gemuese	2026-03-20	158	kg	\N	\N
2302	2026-04-29 12:41:39.288012+00	Bio Mango st	3.25	1	0	3.25	Obst und Gemuese	2026-03-20	158	stk	\N	\N
2342	2026-04-29 12:57:10.171537+00	Bio Peperoni 500g	3.3	1	0	3.3	Obst und Gemuese	2026-03-12	165	g	\N	\N
2293	2026-04-29 12:41:39.288012+00	Bio Vollmilch past 3.9% 1.75l	3.2	1	0	3.2	Milchprodukte, Eier und Alternativen	2026-03-20	158	l	\N	\N
2309	2026-04-29 12:41:39.288012+00	Hydrate+ Antiox 75cl	1.95	1	1.75	0.2	Getr├ñnke (alkoholisch & alkoholfrei)	2026-03-20	158	cl	\N	\N
2382	2026-04-29 12:57:39.84157+00	Coop MH Cashewn├╝sse 200G	3.5	1	0	3.5	Andere	2026-03-06	167	g	\N	\N
2381	2026-04-29 12:57:39.84157+00	Coop MH Mango getrocknet 200G	4.5	1	0	4.5	Andere	2026-03-06	167	g	\N	\N
2365	2026-04-29 12:57:24.631204+00	Coop MH Mango getrocknet 500G	10.75	1	8.95	1.8	Andere	2026-03-10	166	g	\N	\N
2363	2026-04-29 12:57:24.631204+00	Coop Mini Pepperball mit Curry 160G	3.95	1	0	3.95	Andere	2026-03-10	166	g	\N	\N
2353	2026-04-29 12:57:24.630136+00	DAR-VIDA Nature 5Po 208G	3.6	1	0	3.6	Backwaren und Getreide	2026-03-10	166	g	\N	\N
2361	2026-04-29 12:57:24.631204+00	Exoten TT 3.5kg	18.45	1	11.95	6.5	Fleisch, Fisch und pflanzliche Proteine	2026-03-10	166	kg	\N	\N
2369	2026-04-29 12:57:39.84052+00	FG Huusbrot dunkel 450G	2.8	1	0	2.8	Backwaren und Getreide	2026-03-06	167	g	\N	\N
2398	2026-04-29 12:57:59.964898+00	FRECHE FREUNDE Jogh.Ban.Erdbe.pf Himbe.	1.95	1	1.15	0.8	Andere	2026-03-05	169	stk	\N	\N
2399	2026-04-29 12:57:59.964898+00	Freche Freunde Keks Dinkel,Erdbee 100g	3.9	1	2.3	1.6	Andere	2026-03-05	169	g	\N	\N
2306	2026-04-29 12:41:39.288012+00	Heinz Tomato Ketchup 500ml	3.3	1	0	3.3	Gew├╝rze, Kr├ñuter und Saucen	2026-03-20	158	ml	\N	\N
2395	2026-04-29 12:57:49.924388+00	Gillette Rasier-schaum empfind. Haut	2.45	1	1	1.45	Andere	2026-03-05	168	g	\N	\N
2358	2026-04-29 12:57:24.630663+00	Hirz Jogurt 180G Vanille/Himbeer	1.1	2	0	2.2	Milchprodukte, Eier und Alternativen	2026-03-10	166	g	\N	\N
2351	2026-04-29 12:57:10.172631+00	JaMaDu Rieg.Himbeere-Banane 6x24g	3.5	1	0	3.5	Snacks, Apero und Suesswaren	2026-03-12	165	g	\N	\N
2370	2026-04-29 12:57:39.84052+00	Laugengipfel mit Kernen 70G	1.3	1	0	1.3	Backwaren und Getreide	2026-03-06	167	g	\N	\N
2384	2026-04-29 12:57:39.84157+00	Milupa Kinderm├╝sli Fr├╝chte 400G	9.5	1	5.7	3.8	Andere	2026-03-06	167	g	\N	\N
2390	2026-04-29 12:57:39.842092+00	My Baby Hands&Face 6x25 ST	11.7	1	5.85	5.85	Andere	2026-03-06	167	stk	\N	\N
2389	2026-04-29 12:57:39.842092+00	My Baby Water Wipes 6x72ST	19.5	2	9.75	29.25	Andere	2026-03-06	167	stk	\N	\N
2359	2026-04-29 12:57:24.630663+00	Naturafarm Hinterschinken 3x160g	14.55	1	9.95	4.6	Fleisch, Fisch und pflanzliche Proteine	2026-03-10	166	g	\N	\N
2348	2026-04-29 12:57:10.172078+00	Naturaplan Bio Schnitzwasser 1L	1.5	1	0	1.5	Andere	2026-03-12	165	l	\N	\N
2387	2026-04-29 12:57:39.84157+00	Naturaplan Bio Schnitzwasser 1L	1.5	1	0	1.5	Andere	2026-03-06	167	l	\N	\N
2393	2026-04-29 12:57:49.92386+00	Naturaplan Bio Schnitzwasser 1L	1.5	1	0	1.5	Andere	2026-03-05	168	l	\N	\N
2354	2026-04-29 12:57:24.630663+00	Naturaplan Maiswaffeln mit Salz 100G	0.95	1	0	0.95	Andere	2026-03-10	166	g	\N	\N
2356	2026-04-29 12:57:24.630663+00	Nissin SOBA Nudeln Bag Japan.Curry 111G	1.85	1	0	1.85	Andere	2026-03-10	166	g	\N	\N
2357	2026-04-29 12:57:24.630663+00	Nissin Soba Nudeln gebraten Chili 111G	1.85	1	0	1.85	Andere	2026-03-10	166	g	\N	\N
2362	2026-04-29 12:57:24.631204+00	Rispentomaten offen 206	1.25	0.492	0	0.615	Andere	2026-03-10	166	g	\N	\N
2367	2026-04-29 12:57:24.631746+00	Stimorol Peppermint 7x14g (98g)	4.95	1	0	4.95	Snacks, Apero und Suesswaren	2026-03-10	166	g	\N	\N
2366	2026-04-29 12:57:24.631746+00	Valser Prickelnd Zitrone 1.5L	1.85	1	0	1.85	Andere	2026-03-10	166	l	\N	\N
2394	2026-04-29 12:57:49.924388+00	well K├╝chenseife Refill 500ML	3.25	1	1	2.25	Reinigungsmittel und Haushaltsreiniger	2026-03-05	168	ml	\N	\N
2383	2026-04-29 12:57:39.84157+00	Zweifel Chips Paprika Big Pack XXL 380g	8.05	1	4.8	3.25	Snacks, Apero und Suesswaren	2026-03-06	167	g	\N	\N
2374	2026-04-29 12:57:39.841047+00	Zwiebeln Bund	0.7	1	0	0.7	Obst und Gemuese	2026-03-06	167	stk	\N	\N
2360	2026-04-29 12:57:24.631204+00	├äpfel Gala I IP 12.5kg offen PLU 275	2	0.694	0	1.388	Obst und Gemuese	2026-03-10	166	kg	\N	\N
2373	2026-04-29 12:57:39.841047+00	Bio Saisonbirnen offen 130	1.45	0.243	0	0.35235	Obst und Gemuese	2026-03-06	167	g	\N	\N
2371	2026-04-29 12:57:39.841047+00	Butterweggli 70G	0.75	1	0	0.75	Backwaren und Getreide	2026-03-06	167	g	\N	\N
2396	2026-04-29 12:57:59.964898+00	Butterweggli 70G	0.75	1	0	0.75	Backwaren und Getreide	2026-03-05	169	g	\N	\N
2352	2026-04-29 12:57:24.630136+00	Koriander 20G	2.4	1	0	2.4	Gew├╝rze, Kr├ñuter und Saucen	2026-03-10	166	g	\N	\N
2349	2026-04-29 12:57:10.172631+00	conviva Thermometer digital flex. Spitze	9.8	1	1	8.8	Andere	2026-03-12	165	stk	\N	\N
2404	2026-04-29 12:59:59.566067+00	Vitamin Well Reload 50CL	2.25	1	0	2.25	Getr├ñnke (alkoholisch & alkoholfrei)	2026-03-04	171	cl	\N	\N
2405	2026-04-29 12:59:59.566067+00	Vitamin Well Reload 50CL	2.25	0	-2.25	2.25	Getr├ñnke (alkoholisch & alkoholfrei)	2026-03-04	171	cl	\N	\N
2403	2026-04-29 12:59:59.566067+00	Bio Zucchetti 450g	2.5	1	1.95	0.55	Obst und Gemuese	2026-03-04	171	g	\N	\N
2400	2026-04-29 12:57:59.964898+00	Filzkorb Hase mit Pl ├╝schohren weiss	5.95	1	0	5.95	Andere	2026-03-05	169	stk	\N	\N
2406	2026-04-29 12:59:59.566586+00	Vitamin Well Reload 50CL	2.25	1	0	2.25	Getr├ñnke (alkoholisch & alkoholfrei)	2026-03-04	171	cl	\N	\N
2267	2026-04-29 12:41:12.289335+00	Feldschl├Âsschen alk.frei Zitrone DS 50cl	2.1	1	0	2.1	Getr├ñnke (alkoholisch & alkoholfrei)	2026-03-25	156	cl	\N	\N
2278	2026-04-29 12:41:24.763495+00	Guinness Dose 50CL	3.2	1	0	3.2	Getr├ñnke (alkoholisch & alkoholfrei)	2026-03-20	157	cl	\N	\N
2279	2026-04-29 12:41:24.764053+00	Guinness Dose 50CL	3.2	1	0	3.2	Getr├ñnke (alkoholisch & alkoholfrei)	2026-03-20	157	cl	\N	\N
2408	2026-04-29 12:59:59.566586+00	Prix Garantie Cat Pute+Huhn 4x100g	1.15	1	0	1.15	Tierbedarf und Sonstiges	2026-03-04	171	g	\N	\N
2409	2026-04-29 12:59:59.566586+00	Prix Garantie Cat Rind+Kalb 4x100g	1.15	1	0	1.15	Tierbedarf und Sonstiges	2026-03-04	171	g	\N	\N
2410	2026-04-29 12:59:59.566586+00	Prix Garantie Cat Rind+Kalb 4x100g	1.15	1	0	1.15	Tierbedarf und Sonstiges	2026-03-04	171	g	\N	\N
2401	2026-04-29 12:57:59.964898+00	SPAR-BON	0	0	0.7	0	Andere	2026-03-05	169	stk	\N	\N
2407	2026-04-29 12:59:59.566586+00	Vitamin Well Antioxidant 50CL	2.25	1	0	2.25	Andere	2026-03-04	171	cl	\N	\N
2282	2026-04-29 12:41:24.764053+00	Ariel fl├╝ssig Touch of Unstoppables 20WG	12.95	1	7.75	5.2	Reinigungsmittel und Haushaltsreiniger	2026-03-20	157	stk	\N	\N
2281	2026-04-29 12:41:24.764053+00	Ariel Fl├╝ssig Universal 0.9L, 20WG	12.95	1	7.75	5.2	Reinigungsmittel und Haushaltsreiniger	2026-03-20	157	l	\N	\N
2378	2026-04-29 12:57:39.841047+00	Barilla Coll. Mezze Penne Tricolore 500g	3.1	1	0	3.1	Andere	2026-03-06	167	g	\N	\N
2379	2026-04-29 12:57:39.841047+00	Barilla Integrale Farfalle 500g	2.95	1	0	2.95	Andere	2026-03-06	167	g	\N	\N
\.


--
-- Data for Name: integration_config; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.integration_config (key, value_text, value_encrypted, updated_at) FROM stdin;
supercard_session_encrypted	\N	+hazyaUNPt7iODBuOpRP2OIzUsqeCGjD0iS2PbiRNo6yC1ue/Y+4DPOHkUTzB/odWShOY+Cu9XA6YxiK0Wnky3UpRvrjhmRqo2GBIs+N92NS0MeCZZFHZio0Lvg+u09k8p/LrHLvaWcFukfHGYpfvUqJMTh9v5VKJu3qXX36BVexoMogN8enq+1Q38bL8/IrkCEvn14iAAR7Mf7sky9fOT0eCo4h5JDC1hpkf6kPTQmbnZZIQk3evxT1/NZEo2pFMQ0akH8ZkzkbEBnEhkUZ8iVRkYDJl48OLhvJc56qpXVJq5Yo+mAqSqwkT3h6qZFzcI6oDvgSc7k3h2AVx23LgduAiG99Zck8XB2TI3EwUt/y0qzXEwZj00fjLWzWT9d3GJ8dEO/iP/iOp7X621ju0yYsow+3qcxqaYfB1Fh56L0wq72PboLS1pY3HTurLSL8+bkYtjMuGl9mSSoCe/35UFggiCd6bAVlWRDyeAK6ConD4E7M78EQXlk0mQLUF0mk9kRhR2/cjA8y/APT1tTnUDjiNKAZrHmS+k74FV4xZWy909Hf6mWmnbvMkfP9JUcvemtrFR/cpf6mDHHsSPOjQ8Rt6Gjiq4C2uj8xQOp6VKpVgv1CHamPjkUu03o33a8t1SeRwu+sb/+W5DOkhiYzDPJUoknhwek9Rk5+Hhr5DzU9lyA4QPFZ9wYexRpANBDJUc8hLpII6VZexQA+6ZrCc3NaSBVV2nkGMAQJmIpXPOJtzHmKBu+lIivdbGv3cRh1M9z85LWo4zdHkd78Lhyt+MlWFSDqaJwAGF/Vc3+fMBDxVRjUbXF+w+eFQQ7CjnjXbK7JSJ/cKLzfvJYJxPxtA3tCRavmZPJfPpclYP0ULZryOUN6egrypFlI1ySSw97WgmJad9dakF9ylrdBoYPQicWEchEdnmYX9DUK/A3+07KyT+zFTliWb8LSruAZFtk20DW9k6Zx9KhBZG6MvQA0DNkGS+ihlHByLTZilGn46a78sKNDJ7gb2dXFm+xqymqRZ8C+Wvz+h2Aaa5o+xvpPgkkfFCgu8lEYXFUDAsMBqV23gTV2rUSOQImCzHtZ25dq/nLxhOjvbdNuUkNuzXddyLnA5VNqpW3VLrOVy6IyH06uStL+GGsM+4tsuBbYxmvd6xODnO2zuQ==	2026-04-29 15:11:03.222267+00
\.


--
-- Data for Name: profile; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.profile (id, created_at) FROM stdin;
1	2024-12-07 19:07:21+00
\.


--
-- Data for Name: receipt; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.receipt ("Id", "Created_At", "Corp", "Total_Receipt", "Purchase_Date", "Uuid", "Total_Calculated", "Total_R_Open_Ai", "Total_R_Extract", "Id_Profile", "External_Source", "External_Receipt_Id") FROM stdin;
135	2026-04-29 12:18:39.643968+00	Coop	48	2026-04-29	f3463a0f-d9af-4dab-86c6-6b8597be0a52	\N	7	14	\N	supercard	9900110442429042600048004130
136	2026-04-29 12:19:02.289844+00	Coop	116.4	2026-04-27	77a0e52e-bdb2-490b-88f3-6ebe3552e01d	\N	29	34	\N	supercard	9900050524627042600116402543
137	2026-04-29 12:19:09.364645+00	Coop	4.5	2026-04-25	3b807f86-54bf-44d9-8154-02b2b294b0d1	\N	2	6	\N	supercard	9900030142025042600004505458
138	2026-04-29 12:19:16.093951+00	Coop	0.95	2026-04-24	2c8230de-242e-4794-a249-a5f0762d57b1	\N	1	5	\N	supercard	9900030587624042600000951398
139	2026-04-29 12:19:29.71078+00	Coop	31.4	2026-04-23	ce343ef2-3ba0-42f5-a697-e7490ff49af2	\N	9	15	\N	supercard	9900080301123042600031402543
140	2026-04-29 12:24:58.617258+00	Coop	26.1	2026-04-22	e9bab9fc-0d0f-42eb-8aa0-f5fc6be3bd7a	\N	3	8	\N	supercard	9900050585222042600026101398
141	2026-04-29 12:25:06.650257+00	Coop	5.1	2026-04-22	e14a22db-41d0-4b44-a6e0-a13b59a6919e	\N	3	7	\N	supercard	9900030126322042600005101953
142	2026-04-29 12:25:14.706783+00	Coop	2.5	2026-04-18	ed15e8da-8aca-45b5-ab65-0064aaa34ab5	\N	2	6	\N	supercard	9900030530518042600002501398
143	2026-04-29 12:25:24.282161+00	Coop	14.4	2026-04-18	727d52f7-caf3-477e-aa36-5d42251b29ce	\N	5	9	\N	supercard	9900070670818042600014402543
144	2026-04-29 12:25:33.271144+00	Coop	19.95	2026-04-16	61296d1d-110e-4ec9-a34a-ea2eb085aa20	\N	2	6	\N	supercard	9900520664316042600019952543
145	2026-04-29 12:31:01.899041+00	Coop	20.25	2026-04-16	3da8cc31-eff3-46cf-8564-c1fd4204e38c	\N	8	14	\N	supercard	9900090520116042600020252543
146	2026-04-29 12:31:18.223496+00	Coop	123.55	2026-04-13	b2096b5a-fe6c-4331-b5b9-69c16e82f310	\N	32	36	\N	supercard	9900050309013042600123552543
147	2026-04-29 12:31:29.225396+00	Coop	12.7	2026-04-10	95ed9348-4adb-4e55-8c13-1e55b3f33aca	\N	8	12	\N	supercard	9900060076110042600012702464
148	2026-04-29 12:31:37.740905+00	Coop	13.25	2026-04-09	1cd31fb6-08e0-45cb-a093-1fb014583703	\N	7	12	\N	supercard	9900020561109042600013251212
149	2026-04-29 12:31:56.818867+00	Coop	49.15	2026-04-08	bc73235a-ffea-4bf8-953f-b2a3a26a9f7e	\N	19	29	\N	supercard	9900070478408042600049152543
152	2026-04-29 12:39:24.127105+00	Coop	32.6	2026-04-02	f0765768-b2f1-4461-a464-e355e54c0bf1	\N	9	17	\N	supercard	9900030756102042600032601953
154	2026-04-29 12:40:00.818597+00	Coop	10.7	2026-03-27	c9d80838-d9c5-47b8-89e6-5147815ac13e	\N	7	11	\N	supercard	9900100879527032600010702543
155	2026-04-29 12:40:56.867273+00	Coop	0	2026-03-26	9d54f4e2-2481-428f-888b-db764d3d2657	\N	3	10	\N	supercard	9900030594126032600000005455
156	2026-04-29 12:41:12.286697+00	Coop	72.55	2026-03-25	5be95b9d-84cc-424f-8348-83e06267ecb3	\N	20	27	\N	supercard	9900050737525032600072554259
157	2026-04-29 12:41:24.757254+00	Coop	71.3	2026-03-20	5c11de16-b7f9-4dec-b043-35085ca04a13	\N	12	18	\N	supercard	9900120439720032600071304130
158	2026-04-29 12:41:39.284801+00	Coop	69.25	2026-03-20	4ac4d509-d01a-44f4-82c9-69055cd2de31	\N	27	32	\N	supercard	9900040150220032600069252543
159	2026-04-29 12:41:46.50202+00	Coop	4.5	2026-03-18	a3bb043e-81c8-4719-9867-b0cd379164c6	\N	1	5	\N	supercard	9900040190318032600004505455
160	2026-04-29 12:51:13.699138+00	Coop	1.75	2026-03-18	1f5f0351-7008-444c-b66b-4fad66ab3822	\N	2	6	\N	supercard	9900090041418032600001751931
161	2026-04-29 12:51:23.055595+00	Coop	30.15	2026-03-14	b5360a27-6c90-4dd2-ad97-f54bd273b081	\N	9	14	\N	supercard	9900070059014032600030152543
162	2026-04-29 12:51:31.706406+00	Coop	4.3	2026-03-13	67e2e886-272e-47e8-836f-e3d03a6f607f	\N	1	5	\N	supercard	9900020206713032600004304130
163	2026-04-29 12:51:44.319963+00	Coop	18.8	2026-03-13	5b4aba1b-b758-4a8b-bfbf-62f05dbb9a74	\N	10	17	\N	supercard	9900120407413032600018804130
164	2026-04-29 12:51:52.845321+00	Coop	20.85	2026-03-12	d56ec446-4aa8-47e0-9450-421ad7048cd8	\N	3	8	\N	supercard	9900060816812032600020852543
165	2026-04-29 12:57:10.166077+00	Coop	40.55	2026-03-12	2b02ac27-bd8f-4a18-8077-f7ab457ceb47	\N	10	16	\N	supercard	9900060816612032600040552543
166	2026-04-29 12:57:24.624246+00	Coop	70.4	2026-03-10	5404060b-bae2-48ad-9f5e-a24f28a85b11	\N	17	21	\N	supercard	9900060784310032600070402543
167	2026-04-29 12:57:39.838391+00	Coop	87.7	2026-03-06	0c4afb4b-609e-47e3-9ff2-91ed439d5428	\N	24	31	\N	supercard	9900050541406032600087704259
168	2026-04-29 12:57:49.922159+00	Coop	7.2	2026-03-05	ca191cba-d16b-47d3-af8a-69dfd274ebb9	\N	3	7	\N	supercard	9900070853405032600007202543
169	2026-04-29 12:57:59.961217+00	Coop	10.7	2026-03-05	0cd28671-a9ad-486e-878d-790da9d0ebac	\N	6	10	\N	supercard	9900120370105032600010704130
170	2026-04-29 12:59:49.592796+00	Coop	1.5	2026-03-05	cd09dea0-071c-4168-9036-3d816dcbcdf9	\N	1	5	\N	supercard	9900110806205032600001502913
171	2026-04-29 12:59:59.563372+00	Coop	8.5	2026-03-04	67637549-9569-4037-81ff-51f93a7c5ae5	\N	8	13	\N	supercard	9900070832404032600008502543
175	2026-04-29 15:22:24.365543+00	Coop	59.25	2026-04-04	15c30f56-789a-4559-bcbb-2850604fe411	\N	15	19	\N	supercard	9900070653304042600059251953
176	2026-04-29 15:22:32.380055+00	Coop	22.45	2026-04-04	8734bcfb-e18e-42fa-8e75-8c551019903e	\N	5	10	\N	supercard	9900070999604042600022454259
177	2026-04-29 15:22:45.857009+00	Coop	76.95	2026-04-01	183d4db2-0498-4f39-9141-174009973c92	\N	23	31	\N	supercard	9900110095801042600076952543
178	2026-04-29 15:22:56.709231+00	Coop	17.4	2026-02-28	f62bdcd4-d98e-440c-ae53-72f685968a79	\N	11	15	\N	supercard	9900130169328022600017402543
179	2026-04-29 15:23:11.435938+00	Coop	29.4	2026-02-27	84973ebe-df64-40d2-96f8-103f30744406	\N	12	19	\N	supercard	9900060604627022600029402543
\.


--
-- Data for Name: recipe; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.recipe ("Title", "Description", "Cooking_Time", "Category", "Serving", "Color", "Ingredient", "Step_List", "Image", "Id", "Id_Profile") FROM stdin;
\.


--
-- Name: article_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.article_id_seq', 2502, true);


--
-- Name: profile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.profile_id_seq', 1, true);


--
-- Name: receipt_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."receipt_Id_seq"', 179, true);


--
-- Name: recipe_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."recipe_Id_seq"', 1, false);


--
-- Name: article article_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.article
    ADD CONSTRAINT article_id_key UNIQUE ("Id");


--
-- Name: article article_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.article
    ADD CONSTRAINT article_pkey PRIMARY KEY ("Id");


--
-- Name: integration_config integration_config_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.integration_config
    ADD CONSTRAINT integration_config_pkey PRIMARY KEY (key);


--
-- Name: profile profile_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile
    ADD CONSTRAINT profile_pkey PRIMARY KEY (id);


--
-- Name: receipt receipt_Id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.receipt
    ADD CONSTRAINT "receipt_Id_key" UNIQUE ("Id");


--
-- Name: receipt receipt_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.receipt
    ADD CONSTRAINT receipt_pkey PRIMARY KEY ("Id");


--
-- Name: recipe recipe_Id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recipe
    ADD CONSTRAINT "recipe_Id_key" UNIQUE ("Id");


--
-- Name: recipe recipe_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recipe
    ADD CONSTRAINT recipe_pkey PRIMARY KEY ("Id");


--
-- Name: ux_receipt_external_source_id; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX ux_receipt_external_source_id ON public.receipt USING btree ("External_Source", "External_Receipt_Id") WHERE (("External_Source" IS NOT NULL) AND ("External_Receipt_Id" IS NOT NULL));


--
-- Name: article article_Receipt_Id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.article
    ADD CONSTRAINT "article_Receipt_Id_fkey" FOREIGN KEY ("Receipt_Id") REFERENCES public.receipt("Id") ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: receipt receipt_Id_Profile_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.receipt
    ADD CONSTRAINT "receipt_Id_Profile_fkey" FOREIGN KEY ("Id_Profile") REFERENCES public.profile(id) ON DELETE CASCADE;


--
-- Name: recipe recipe_Id_Profile_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recipe
    ADD CONSTRAINT "recipe_Id_Profile_fkey" FOREIGN KEY ("Id_Profile") REFERENCES public.profile(id) ON DELETE CASCADE;


--
-- Name: profile; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.profile ENABLE ROW LEVEL SECURITY;

--
-- PostgreSQL database dump complete
--

